#
# Copyright 2024. Clumio, Inc.
#
# Pre-commit config for the Clumio cdf repository.
#
# https://pre-commit.com
# https://github.com/clumio-oss/pre-commit
# https://github.com/clumio-oss/pre-commit-hooks
# https://github.com/clumio-code/pre-push-hooks
#
# To install the hooks run (bin/pip_sync will do that as well):
#   `pre-commit install -t pre-commit -t pre-push`
#
# If you need to disable a hook temporarily (hooks can be wrong sometimes) you
# can simply add `SKIP=<hook-id` before the git commit command:
#  `SKIP=gray git commit -m 'CLUMIO-1234: skipped gray'`
#
---
repos:
  #  CENG-1675: Git hook to prevent pushes to protected branches
  - repo: https://github.com/clumio-code/pre-push-hooks
    rev: v0.2
    hooks:
      - id: check-branch-for-push
        args: [
          '--pattern', '^user/.*',
          '--pattern', '^team/.*',
          '--pattern', '^revert-[0-9]+-user/.*'
        ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1048']
        stages: [commit, manual]

  # CENG-1184: pre-commit hook: require @clumio.com email address
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.16.2
    hooks:
      - id: check-git-config-email
        args: ['--domains', 'clumio.com']
        stages: [commit]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version. Keep in sync with the version in requirements.txt.
    rev: v0.5.5
    hooks:
      # Run the linter.
      - id: ruff
        stages: [commit]
      # Run the formatter. Would conflict with gray which has more features for now.
      - id: ruff-format

  # yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    # When updating the rev here, update the yamllint entry in requirements.txt.
    rev: v1.35.1
    hooks:
      - id: yamllint
        stages: [commit]
